### ISSUE TITLE
How to alert when message has been sent?

### ISSUE THREAD

**Issue by sambo-visal** [doorbell/ios-sdk#10]
Hello! This is such a great feedback library. When i click send button with empty textField then it will alert error which it is message is required. But i want to handle when user clicks on send button with textField is not empty then i want to alert user that message has been sent or something.

How can I archive something like this?

**Comment by manavo** [comment]
Hi, and sorry for the late reply!

As you can see from the example code in the readme file, there is a callback which lets you know when the call is completed:

```objc
Doorbell *feedback = [Doorbell doorbellWithApiKey:appKey appId:appId];
[feedback showFeedbackDialogInViewController:self completion:^(NSError *error, BOOL isCancelled) {
    if (error) {
        NSLog(@"%@", error.localizedDescription);
    }
}];
```

So if there isn't an error, and it if wasn't cancelled, it means the message was sent successfully and you can notify the user!

Would that work for you?

Thanks,
Phil

**Comment by sambo-visal** [comment]
Thank for your reply! 
This is what I have tried but I have one issue in which when I click on cancel button or sent button and then `self.showSnackbarMessage()` always execute.

That is the problem I want to let you know. If user clicks on cancel button then no need to alert anything except send button and message is successfully sent.

         doorbell?.showFeedbackDialog(in: self, completion: { (error, cancel) in
                    
                    if let error = error {
                        
                        print("This is error \(error.localizedDescription)")
                    } else {
                        print("No error")
                        if !cancel {
                            self.showSnackbarMessage(title: languageHelper.getSuccessFeedback())
                        } else {
                            print("User clicks cancel button.")
                        }
                    }
                    
                    
                    
                }, animated: true)

That meant the callback block always return false no matter I click on cancel or send button.
I want to alert message when message successfully sent only. But I don't know why when I clicked on cancel button and message also alert.

**Comment by manavo** [comment]
So the issue is that `cancel` appears to be `false`, even when the dialog is canceled?

I'll have a look at this, thanks for letting me know!

**Comment by manavo** [comment]
You're right, the bug seems to be here: https://github.com/doorbell/ios-sdk/blob/master/Classes/Doorbell.m#L164, that should return `YES` instead of `NO` when calling the block. I'll try and get this fixed ASAP!

Thanks for letting me know!

**Comment by sambo-visal** [comment]
You're welcome!
Hope to see it fix ASAP 👍

**Comment by manavo** [comment]
Thanks again for letting me know about this, I've just pushed version `0.1.3` which fixes this!

**Comment by sambo-visal** [comment]
Now I will clone and work on it.
Thank for your hard work. And will let you know if anything happen once again.
