### ISSUE TITLE
Message when there is no Internet Connection is too long

### ISSUE THREAD

**Issue by SalMinoz** [doorbell/ios-sdk#11]
When user send a message without Internet Connection it seems like the error message it too long. So, it makes user confusion. 

![screen shot 2562-01-21 at 8 50 24 pm](https://user-images.githubusercontent.com/46895232/51478515-3adc0400-1dbe-11e9-9e1f-8b7c7fd93387.png)

Please kindly fix this issue. Thank for your hard work.

**Comment by manavo** [comment]
Thank you very much for the heads up! I'll look into fixing this.

Is that the default error popping up? Or is that how you're displaying it?

**Comment by SalMinoz** [comment]
@manavo It's a default message. When I disconnected the internet and then I tried to send a message after that this long message was popping up like that. If a message is too long like that as a user will not able to understand.

**Comment by manavo** [comment]
Yep, absolutely! I'll try and get this fixed ASAP!

Thanks for letting me know!

**Comment by SalMinoz** [comment]
Yep, sir! Please fix it ASAP! I really need for my project.

**Comment by manavo** [comment]
Hey! I've just tagged `0.1.4`, so if you update to that the error will display better!

Thanks
