### ISSUE TITLE
No support for dark mode in default dialog

### ISSUE THREAD

**Issue by vilimas** [doorbell/ios-sdk#12]
The default feedback form doesn't support dark mode. The biggest problem that email text field placeholder hardly visible. 

![IMG_0659](https://user-images.githubusercontent.com/3592381/84112714-f6dcb400-aa31-11ea-83b9-a3a798873b44.jpg)

**Comment by manavo** [comment]
Thanks for reporting the issue @vilimas! I'll try and add some sensible defaults for dark mode support!

**Comment by manavo** [comment]
This has now been added @vilimas, sorry for the delay!
