### ISSUE TITLE
App crashes when sending feedback on iOS 12.5.3

### ISSUE THREAD

**Issue by MarkBorazio** [doorbell/ios-sdk#15]
I am testing my app on a couple of physical devices, and my older device seems to always crash when I send the feedback.
Here is what I am seeing:
- iPhone 8, iOS 14.1 - Never crashes
- **iPhone 6, iOS 12.5.3 - Always crashes**

_The pod spec does specify an iOS version of 13, but I am not sure if that has anything to do with it._

I am using version `0.3.0` of the sdk.

# Details

The app crashes with a `signal SIGABRT` in `Doorbell.m` at line `466`:
```objc
if ([response isKindOfClass:[NSHTTPURLResponse class]]) {
```

I checked the `response` object, and got this:
```
<NSHTTPURLResponse: 0x28008eac0> { URL: https://doorbell.io/api/applications/<REDACTED APP ID>/submit?sdk=ios&version=0.3.0&key=<REDACTED APP KEY> } { Status Code: 201, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Cache-Control" =     (
        "no-cache, private"
    );
    "Content-Length" =     (
        14
    );
    "Content-Type" =     (
        "text/plain; charset=UTF-8"
    );
    Date =     (
        "Sat, 24 Jul 2021 12:03:02 GMT"
    );
    Server =     (
        Caddy
    );
    Status =     (
        "201 Created"
    );
    "access-control-allow-headers" =     (
        "*"
    );
    "access-control-allow-methods" =     (
        "OPTIONS, GET, POST"
    );
    "access-control-request-method" =     (
        "*"
    );
} }
```

Visiting the URL in a browser gave me this message:
```
"Invalid invocation, missing JSONP callback"
```

Lastly, and maybe I am wrong about this, but the response shouldn't have the app key in it, right?

**Comment by manavo** [comment]
Hi @MarkBorazio, sorry for the trouble here!

Just to get the easy ones answered first:

1. The response doesn't return the app key, but when you print/debug the response it shows the URL which was called, and that has the key shown there. The HTTP response from the server doesn't return the key again.
2. The `Invalid invocation, missing JSONP callback` issue is that opening the endpoint in the browser makes a `GET` request to that endpoint, whereas the iOS SDK makes a `POST` request.

I'm not sure about the crash itself, I'll see if I can test and see why that's happening. That line certainly looks innocent enough!

Is the debug response you've included here from the iOS 12 device that always crashes?

Thanks,
Phil

**Comment by MarkBorazio** [comment]
@manavo 
Good to know about those two points.

Yes, the debug response is from the iOS 12 device (when it had crashed).

**Comment by manavo** [comment]
I've just tried to run it, but with adding support for dark mode it has set the minimum platform version to 13 now.

So on a 12.4 simulator I can't even run a demo app which includes Doorbell's SDK.

**Comment by MarkBorazio** [comment]
From what I can see, the only reason iOS 13 is a minimum requirement is because we are using colours only available on iOS 13 and above.
It should be pretty easy to fix that up so it uses the old colours when below iOS 13.

If you want, I can create a PR for that and check if it fixes this crashing issue (I should then not have to specify iOS 13 in my podfile).

**Comment by manavo** [comment]
If you're able to replace the colors with other ones, and still keep working with dark mode, I'd definitely be happy to merge that!

**Comment by MarkBorazio** [comment]
@manavo 
I can confirm that lowering the minimum iOS version fixes the crash.
Here is the PR: #16.

**Comment by manavo** [comment]
Thanks @MarkBorazio! I'll get it tested and merged next week!

**Comment by manavo** [comment]
Thanks again for the PR @MarkBorazio! Needed 1 or 2 little adjustments (another change which is only supported from iOS 10 and above), but that's all done now!

**Comment by manavo** [comment]
Version 0.4.0 has been tagged and released in Cocoapods!
