### ISSUE TITLE
SwiftUI integration

### ISSUE THREAD

**Issue by tomsun3** [doorbell/ios-sdk#17]
Hi! Is it possible to use it with/integrate it into SwiftUI? If so, could you add an example to the main page?

Thanks in advance :)

**Comment by manavo** [comment]
Hi @thomasmo3!

I'd need to look into that, not 100% sure what that would look like. But I'm guessing something along these lines would help get it to work!

https://www.captechconsulting.com/blogs/combining-swiftui-with-viewcontrollers

Thanks,
Phil

**Comment by tomsun3** [comment]
Hi @manavo,

thanks for your quick response!
That should work, but I think there might be a better way to add it into a SwiftUI view directly. Currently, I'm also not sure how. Although, this would be great for other users as well to be added to the instructions of Doorbell integration for iOS, I think.

all the best,
Thomas

**Comment by manavo** [comment]
Hi @thomasmo3,

I've just been doing some tests for this, and this seems to work for SwiftUI:

```swift
// In your View, define a button or something to trigger the feedback dialog
Button(action: feedback) {
    Label("Feedback", systemImage: "plus")
}

// In the same struct, create a function that can be called to initialize Doorbell
private func feedback() {
    var currentKeyWindow: UIWindow? {
      UIApplication.shared.connectedScenes
        .filter { $0.activationState == .foregroundActive }
        .map { $0 as? UIWindowScene }
        .compactMap { $0 }
        .first?.windows
        .filter { $0.isKeyWindow }
        .first
    }

    var rootViewController: UIViewController? {
      currentKeyWindow?.rootViewController
    }

    
    let appId = "ID-HERE"
    let appKey = "KEY-HERE"

    let feedback = Doorbell.init(apiKey: appKey, appId: appId)

    feedback!.showFeedbackDialog(in: rootViewController, completion: { (error, cancelled) -> Void in
        if (error?.localizedDescription != nil) {
            print(error!.localizedDescription);
        }
    })
}
```

Would something like this work for you?

Thanks,
Phil

**Comment by tomsun3** [comment]
Thank you, @manavo  !

Works pretty well. This sould be added to the documents for your users.
I decided to create my custom UI now and directly use your library to send the feedback.
Your provided feedback dialog does not look really beautiful IMHO, maybe this might need some improvement :) (Also, I'm not creating an issue for that now...

All the best and read you soon,
Thanks, also for our email communication,
Thomas

**Comment by manavo** [comment]
Great to hear that it works at least, it's a good starting point! Thanks for confirming @thomasmo3!

I'll add this to the docs for now since it gets it working. And yes I do agree that it wouldn't really win any design awards, but I'll see what I can do about that too :)

Thanks,
Phil
