### ISSUE TITLE
XCode warnings regarding Umbrealla headers

### ISSUE THREAD

**Issue by tomsun3** [doorbell/ios-sdk#18]
Hi guys!

Still getting 2 warnings for the library:

```
Umbrella header for module 'Doorbell' does not include header 'DoorbellDialog.h'
Umbrella header for module 'Doorbell' does not include header 'UIWindow+Doorbell.h'
```

Thanks,
Thomas

**Comment by manavo** [comment]
Hi @thomasmo3, really sorry about that!

Could I trouble you for a bit more information with this?

1. Which version of the Doorbell SDK does this happens with?
2. Which language are you using? (Swift? Obj-c?)

Thanks,
Phil

**Comment by tomsun3** [comment]
Hi Phil @manavo ,

This occurs using the latest version (`master` branch), but already for `0.4` and previous versions I got that. I have the warnings until I started using your SDK and compiling it in my Xcode project as package dependency. At first sight, they do not appear, but when cleaning and building everything, these warnings occur. (Independent of Xcode version)

Thanks,
Thomas

P.S.: I'm using Swift (and SwiftUI)

**Comment by manavo** [comment]
Thanks for letting me know @thomasmo3! My demo apps here where I test the SDK aren't showing me this, so I'll have to do some more digging to see what the issue is.

One demo app is in Objective C and loading the integration through Cocoapods, and the other one is in Swift using Swift Package Manager.

Being a Swift project, I'm guessing you're also using SPM?

**Comment by tomsun3** [comment]
Yes sir, I'm using SPM and the master branch of your package on GitHub. I get the warning in the "Issue navigator" tab in XCode, also when cleaning the project and building again. 

Thanks for solving it @manavo !

**Comment by tomsun3** [comment]
BTW: my iOS deployment target is set to iOS 15.0. (also appears for iOS 16)

@manavo

**Comment by manavo** [comment]
Well that's weird. Literally just re-opened XCode to see if I can change the deployment target, and I'm now seeing the same you mentioned before...

<img width="420" alt="CleanShot 2022-08-16 at 22 05 37@2x" src="https://user-images.githubusercontent.com/259487/184985108-42e317e5-7468-4624-b6b1-0851c55766ea.png">

So definitely something I can at least debug now and try and see what's happening!

**Comment by manavo** [comment]
Can I trouble you to load the `master` branch and see how it looks now @thomasmo3?

Thanks,
Phil

**Comment by tomsun3** [comment]
Looks great! Warnings disappeared (for now ;-P). Thank you very much! @manavo

**Comment by manavo** [comment]
Thanks for confirming! I’ll make a new release with the changes
