### ISSUE TITLE
Turn on TravisCi

### ISSUE THREAD

**Issue by jaredsburrows** [doorbell/ios-sdk#6]
@manavo Let me know when you added this repo to travisci

**Comment by manavo** [comment]
@jaredsburrows it is there already: https://travis-ci.org/doorbell/ios-sdk

**Comment by jaredsburrows** [comment]
Great!

Jared Burrows

_jaredsburrows@gmail.com jaredsburrows@gmail.com_
LinkedIn: https://www.linkedin.com/in/jaredsburrows
